apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-users
  name: ms-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-users
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-users
    spec:
      containers:
      - image: example-grpc-launcher-users-ms
        name: example-grpc-launcher-users-ms
        imagePullPolicy: Never
        command: ["npm"]
        args: ["run", "start:dev"]
        resources: {}
status: {}
