apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-users
  name: ms-users
spec:
  ports:
  - name: "50051"
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: ms-users
  type: ClusterIP
status:
  loadBalancer: {}
